### ISSUE TITLE
Sonarr: NZBIndex.com wants the URL parameter 'key' not 'apikey'

### ISSUE THREAD

**Issue by tggman** [Servarr/Wiki#181]
Indexer:  NZBIndex.com

The "key" URL parameter works:
https://api.nzbindex.com/api?t=caps&key=REDACTED

whereas the "apikey" URL parameter Sonarr passes returns Forbidden:
https://api.nzbindex.com/api?t=caps&apikey=REDACTED

I've tried several workarounds and I even read the Docs :) but can't seem to find a fix for this issue. Am I missing something obvious?

**Log**:
2022-08-24 12:44:38.5|Warn|HttpClient|HTTP Error - Res: [GET] https://api.nzbindex.com/api?t=caps&apikey=(removed) 403.Forbidden (9 bytes)
Forbidden
2022-08-24 12:44:38.5|Warn|Newznab|Unable to connect to indexer

[v3.0.9.1549] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://api.nzbindex.com/api?t=caps&apikey=(removed)   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 281
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 64
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Cache\Cached.cs:line 104
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Core.Indexers.Newznab.Newznab.get_PageSize() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 24
   at NzbDrone.Core.Indexers.Newznab.Newznab.GetRequestGenerator() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 28
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 336
Forbidden

2022-08-24 12:44:38.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2022-08-24 12:44:41.6|Warn|HttpClient|HTTP Error - Res: [GET] https://api.nzbindex.com/api?t=caps&apikey=(removed) 403.Forbidden (9 bytes)
Forbidden

[AB#3676](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3676)

**Comment by bakerboy448** [comment]
This has nothing to do with the wiki?

newznab spec is apikey.  If your indexer doesn't abide by newznab standards then it cannot be used in \*arrs

**Comment by tggman** [comment]
Understood and sorry for opening the issue in the wrong spot.  Take care
